export const english ={

        profilePhoto: 'Profile Photo',
        chooseOption: 'Choose an option',
        openCamera: 'Open Camera',
        openGallery: 'Open Gallery',
        openFileManager: 'Open File Manager',
        cancel: 'Cancel',
        triggerNotification: 'Trigger Notification',
        layout: 'Layout',
        themes: 'Themes',
        sound: 'Sound',
        storedata: 'Store Data',
        acceptanceofUse: 'Acceptance of Use',
        logout: 'Logout',
        subtotal: 'Subtotal',
        tax: 'Tax',
        total: 'Total',
        checkout: 'Checkout',
        paymentMethod: 'Payment Method',
        cash: 'Cash',
        card: 'Card',
        name: 'Name',
        email: 'Email',
        address: 'Address',
        city: 'City',
        country: 'Country',     
        pay: 'Pay',
        settings: 'Settings',
    
}